### ISSUE TITLE
Add Customized UI css themes and templates

### ISSUE THREAD

**Issue by michellezhuogg** [shaka-project/shaka-player#3246]
Our [UI library](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html) ​is customizable, and easy to configure following the [tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html). For example, the developers can set the sizes and colors of the control elements.

This is a feature we’d like more developers to know, and we'd like to have one or two customized css themes and templates to showcase our UI customization possibilities, similar to the [Chrome themes](https://chrome.google.com/webstore/category/themes). The developers can apply the theme directly by copying the css styles.

Instructions:
1. Create an UI configuration with the customized layouts, or a css style sheet with customized css styles in your own Github repository.
2. Send us a link to your UI configuration or your css style sheet, and a screenshot.
3. We'll add your theme to our tutorial.

Besides, we need to improve our document regarding how to customize the css styles :)

Thank you!

**Comment by nbcl** [comment]
I find the idea of having a custom theme as an example on the tutorial a great start point for new developers who would be interested on customizing their UI.

I would really like to be assigned on this issue!

@michellezhuogg

**Comment by CodeDotJS** [comment]
@michellezhuogg please fix the links related to *UI Library* and *Tutorial*.  Currently, they are pointing to localhost.

**Comment by nbcl** [comment]
@CodeDotJS, here are the intended links:

1. UI Library: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html
2. Tutorial: https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html

Hope this helps!

**Comment by Ketan2010** [comment]
@michellezhuogg Sir, 
Using current UIConfiguration for css we can only change color of seek bar (seekBarColors) and volume bar (volumeBarColors).
So are you expecting theme and template by customizing css of only these two controls? 
also you are asking for link of separate css file but customizations can be done inside ui.configure(). can you please clarify?
Thanks!

**Comment by TheModMaker** [comment]
You can also style the UI with standard CSS using our mostly undocumented CSS classes.  For example, you can make the current time red with:

```css
.shaka-current-time, .shaka-current-time[disabled] {
  color: red;
}
```

**Comment by Ketan2010** [comment]
@michellezhuogg, @TheModMaker 

css style sheet with undocumented CSS classes:

```
.shaka-current-time, .shaka-current-time[disabled] {
     color: rgb(245, 160, 64);
}
.material-icons-round{
     color: rgb(245, 160, 64);
}
```

UIcustomized css styles:

```
const config = {
	'seekBarColors': {
		base: 'rgba(255, 255, 255, 0.3)',
		buffered: 'rgb(240, 206, 168)',
		played: 'rgb(245, 160, 64)',
	},
	'volumeBarColors':{
		base: 'rgba(255, 255, 255, 0.3)',
		level: 'rgb(245, 160, 64)',
	}
  };
```

Results:
![image](https://user-images.githubusercontent.com/57591621/112275778-f9995480-8ca5-11eb-94c5-768bbe4d392c.png)

![image](https://user-images.githubusercontent.com/57591621/112275904-1df53100-8ca6-11eb-9f26-02a8ba58e45c.png)

![image](https://user-images.githubusercontent.com/57591621/112275978-31a09780-8ca6-11eb-8376-4ba8c26199b9.png)

**Comment by nbcl** [comment]
I found out this dark theme works very well for me on development, as it a  a bit easier on the eyes and does not conflict when seeing videos that have dark backgrounds either.

If anyone is looking forward to expand it to include `ui.configure()` styling, feel free to do it and make sure to add a couple of screenshots!

```css
/* Overflow menu style */

.shaka-overflow-menu {
    background-color: rgb(35, 35, 35);
    color: rgb(255, 255, 255);
}

.shaka-overflow-menu button:hover {
    background-color: rgb(45, 45, 45);
}

.shaka-overflow-button-label {
    color: rgb(245, 245, 245);
}

.shaka-current-selection-span {
    color: rgb(202, 202, 202);
}

.material-icons-round {
    color: rgb(230, 230, 230);
}

/* Overflow sub menu style */

.shaka-settings-menu {
    background-color: rgb(35, 35, 35);
    color: rgb(255, 255, 255);
}

.shaka-settings-menu button {
    color: rgb(255, 255, 255);
}

.shaka-settings-menu button:hover {
    background-color: rgb(45, 45, 45);
}
```
