### ISSUE TITLE
Missing calc() from release CSS in v3.1.7, v3.2.5, and v3.3.3

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#4155]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**
v3.3.3

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
No

**Are you using the demo app or your own custom app?**
N/A

**If custom app, can you reproduce the issue using our demo app?**
N/A

**What browser and OS are you using?**
N/A

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
N/A

**What are the manifest and license server URIs?**

N/A

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

N/A

**What did you do?**

Apparently, I made some mistakes when cherry-picking for our most recent round of releases.  v3.1.7, v3.2.5, and v3.3.3 are all affected.

During a very messy upgrade-downgrade-upgrade process w/ less.js, calc() statements got incidentally removed, then added back.  Commits that were cherry-picked to the release branches included the removal, but not the restoration.  As a result, the CSS in those releases have several errors:

```css
.shaka-skip-ad-container {
  right: (100 - @bottom-controls-width) / 2 * -1;
}
.shaka-play-button {
  padding: @play-button-size-percentage / 2;
}
.shaka-spinner {
  padding: @spinner-size-percentage / 2;
}
.range-container() {
  margin: (@thumb-size - @track-height)/2 6px;
}
.range-element() {
  top: (@track-height - @thumb-size) / 2;
}
.shaka-tooltips-on {
  & > [class*="shaka-tooltip"] {
    &:hover:after, &:focus-visible:after, &:active:after {
      line-height: @material-icons-width / 2;
      bottom: @material-icons-width + 5px;
      left: @material-icons-width / 2;
    }
  }
}
```

This was only caught because the final CSS from the v3.3.3 release was rejected by some internal tools when other Google projects tried to consume it. 😞
